name: Setup PHP and install dependencies
description: Install the right version of PHP (according to strategy.matrix.php) as well as the project depencencies (via Composer)
runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Install dependencies
      run: composer install --no-progress
      shell: sh
